name: Profile Views Counter
on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  count-views:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get Repository List
        id: repo-list
        uses: actions/github-script@v6
        with:
          script: |
            const { data: repos } = await github.rest.repos.listForUser({
              username: 'solveditnpc',
              type: 'all'
            });
            return repos.map(repo => repo.name);

      - name: Update Views Counter for Each Repository
        uses: antonkomarev/github-profile-views-counter@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_ID: solveditnpc
          COUNT_PRIVATE: true
